version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${TAG}
    ports:
      - ${UIPORT}:${UIPORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${TAG}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${TAG}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
volumes:
  post_db:
networks:
  back_net:
  front_net:
